# Generated by Django 2.2.16 on 2021-08-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210824_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете загрузить изображение.', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
